### ISSUE TITLE
Support setting time limit, and getting solve time

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/MiniZinc.jl#38]
MiniZinc seems to have an option:
```
  --time-limit <ms>
    Stop after <ms> milliseconds (includes compilation and solving).
```
see [here](https://stackoverflow.com/questions/52800633/time-limit-imposed-in-command-line-does-not-seem-to-constraint-run-time).

There is also:
```
  --output-time
    Print timing information in the FlatZinc solution stream.
```
though maybe we can just time the MiniZinc run time using Julia.

CC @odow

**Comment by odow** [comment]
> though maybe we can just time the MiniZinc run time using Julia.

This is likely a lot easier

**Comment by odow** [comment]
Let me take a crack
