### ISSUE TITLE
Support getting SolverVersion

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/MiniZinc.jl#40]
@odow what's the best way to do this?

**Comment by odow** [comment]
x-ref https://github.com/jump-dev/Pavito.jl/issues/71

**Comment by odow** [comment]
This depends whether you want the libminizinc version or the MiniZinc.jl version

**Comment by odow** [comment]
And it also depends on the underlying solver. I don't know if this makes sense to return.

**Comment by chriscoey** [comment]
I think the libminizinc version makes sense

**Comment by odow** [comment]
Then we should just hard-code it

**Comment by odow** [comment]
Unless you could parse `minizinc -v` or something
