### ISSUE TITLE
CP-SAT solver

### ISSUE THREAD

**Issue by 1991jhf** [jump-dev/MiniZinc.jl#57]
Does minizinc.jl support calling CP-SAT solver?

**Comment by odow** [comment]
MiniZinc.jl is not a full interface to MiniZinc. It is limited to the MathOptInterface API: https://github.com/jump-dev/MiniZinc.jl#use-with-mathoptinterface

But if you have CP-SAT installed, you can probably use it by passing the appropriate path to the `.msc` file. I don't have CP-SAT installed, so I haven't tried this though, and I don't have any suggestions for exactly what is required.

**Comment by odow** [comment]
Closing as won't-fix. We don't have a specialized interface to CP-SAT. If you need any other help using MiniZinc.jl, feel free to start a post on our forum: https://discourse.julialang.org/c/domain/opt/13.
