### ISSUE TITLE
[upstream] wrong number of solutions 

### ISSUE THREAD

**Issue by blegat** [jump-dev/MiniZinc.jl#84]
CP experts told le during the presentation thatvthis should be 92, not 52. They checked writing the problem directly in MiniZinc and using Chuffed and they got 92 so it seems to be a problem in the minizinc writer here
https://github.com/jump-dev/MiniZinc.jl/blob/5e9241bd702b3a512ee6e5c964e2d23ae2535580/test/examples/nqueens_solveall.jl#L27

**Comment by odow** [comment]
I changed this when I updated to a newer version of Chuffed: 
https://github.com/jump-dev/MiniZinc.jl/commit/d3fef2506657af53b1b7cee07150fb16f60c85f2

Let me take a look

**Comment by odow** [comment]
The `.mzn` file is correct:
```raw
shell> cat test.mzn
var 1 .. 8: x1;
var 1 .. 8: x2;
var 1 .. 8: x3;
var 1 .. 8: x4;
var 1 .. 8: x5;
var 1 .. 8: x6;
var 1 .. 8: x7;
var 1 .. 8: x8;
var int: x9;
var int: x10;
var int: x11;
var int: x12;
var int: x13;
var int: x14;
var int: x15;
var int: x16;
var int: x17;
var int: x18;
var int: x19;
var int: x20;
var int: x21;
var int: x22;
var int: x23;
var int: x24;
constraint 1*x1 + -1*x9 = -1;
constraint 1*x2 + -1*x10 = -2;
constraint 1*x3 + -1*x11 = -3;
constraint 1*x4 + -1*x12 = -4;
constraint 1*x5 + -1*x13 = -5;
constraint 1*x6 + -1*x14 = -6;
constraint 1*x7 + -1*x15 = -7;
constraint 1*x8 + -1*x16 = -8;
constraint 1*x1 + -1*x17 = 1;
constraint 1*x2 + -1*x18 = 2;
constraint 1*x3 + -1*x19 = 3;
constraint 1*x4 + -1*x20 = 4;
constraint 1*x5 + -1*x21 = 5;
constraint 1*x6 + -1*x22 = 6;
constraint 1*x7 + -1*x23 = 7;
constraint 1*x8 + -1*x24 = 8;
constraint alldifferent([x1, x2, x3, x4, x5, x6, x7, x8]);
constraint alldifferent([x9, x10, x11, x12, x13, x14, x15, x16]);
constraint alldifferent([x17, x18, x19, x20, x21, x22, x23, x24]);
solve satisfy;
include "alldifferent.mzn";
```
and if I solve with Chuffed 0.13 in minizincIDE it also finds 52 solutions. So this is not a bug in MiniZinc.jl

**Comment by odow** [comment]
I don't think that is true:
<img width="916" alt="image" src="https://github.com/user-attachments/assets/b7e2f6a3-a979-4081-b720-58b4ed75ad08">

**Comment by odow** [comment]
We updated in a big jump: https://github.com/chuffed/chuffed/compare/0.10.4...0.13.2

I haven't bisected, but a scan of the issues shows:

 * https://github.com/chuffed/chuffed/issues/10

and then this temporary fix:

 * https://github.com/chuffed/chuffed/pull/108

I'll open an issue and discuss with them.

**Comment by odow** [comment]
I've opened an issue in Chuffed: https://github.com/chuffed/chuffed/issues/200. This is their bug. With the same `.mzn` file, other solvers like Gecode can find the correct number of solutions.
